### ISSUE TITLE
/bsadmin limits recalculate

### ISSUE THREAD

**Issue by YellowZaki** [BentoBoxWorld/Limits#10]
**Is your feature request related to a problem? Please describe.**
I've just discovered my IslandBlockCount folder is empty (it used to have files) and anybody has limits, so I would like to recalculate all limits again.

**Describe the solution you'd like**
It would recalculate the limits of all islands for admins who install this addon after they already have islands.

**Comment by tastybento** [comment]
To do this would need something similar to the Level addon code to run a full island scan on each island to count existing blocks. Not impossible, but quite a lot of computing.

**Comment by Poslovitch** [comment]
Closing this issue, as #14 was merged.
