### ISSUE TITLE
Blocks not getting removed after you summon a wither etc

### ISSUE THREAD

**Issue by Tobydj** [BentoBoxWorld/Limits#103]
**Description**
I use the limits addon to control soul sand to prevent too many bubble columns. I have it limited to 8. Players use 4 for growing netherwart etc and the other 4 is so they can summon the wither. However after the wither has been summoned and killed the blocks remain when doing /gamemode limits. It has also been suggested that this might also happen with other mobs such as iron and snow golems.

**Steps to reproduce the behavior:**

1. limit soul sand
2. place 4 soul sand to summon a wither
3. check the /gamemode limits
4. summon wither and kill
5. check /gamemode limits again
6. the block remain!

**Expected behavior**
Expected behavior is that the 4 soul sand blocks would also be removed upon summoning the wither.

**Screenshots**

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): []
 - Java Version: [e.g. Java 8]
 - BentoBox version: [e.g. 1.7.2.21]
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
 - Other plugins? [Do '/plugins' and copy/paste from the console]

**Additional context**

**Comment by tastybento** [comment]
What build of Limits are you using? Try the latest one.

**Comment by Espantonius** [comment]
He has put the same thing in the post i made a few days ago: https://github.com/BentoBoxWorld/Limits/issues/97#issuecomment-695338164

**Comment by Tobydj** [comment]
I'm using build b-234 and it's still not working. The blocks remain as counted within the limits addon even though they have been turned into a wither.

**Comment by BONNe** [comment]
It is bug, I am not saying that it should not be fixed but...
Why you want to limit soulsand?

**Comment by Tobydj** [comment]
To stop excessive use of bubble columns.

**Comment by tastybento** [comment]
Aha, I did not understand. I thought the blocks were remaining in the game but this is that they remain counted as being there. Got it!
