### ISSUE TITLE
LimitsJoinPermCheckEvent with update

### ISSUE THREAD

**Issue by Guillaume-Lebegue** [BentoBoxWorld/Limits#111]
**Is your feature request related to a problem? Please describe.**
Using the Upgrades addon with Limits means that it's not possible to use permission.
Even with permission about limits not in upgrades

**Describe the solution you'd like**
Upgrade the LimitsJoinPermCheckEvent to be fired for each permission, with block type in it.
To select which permission to stop.

**Describe alternatives you've considered**
Redoing the permission part in upgrades.

**Additional context**
#101 
https://github.com/BentoBoxWorld/Upgrades/issues/29

**Comment by tastybento** [comment]
Please check #112 and let me know if this will meet your needs.

**Comment by Guillaume-Lebegue** [comment]
Yes, I think that should be perfect, thanks
