### ISSUE TITLE
The withers explodes immediately when summoned

### ISSUE THREAD

**Issue by Wolfbros** [BentoBoxWorld/Limits#118]
**Description**
If you create a withers, it will explode instantly with no loading time. (With addon limits 1.15.0)

**Steps to reproduce the behavior:**
1. Go to your cave
2. Spawn a wither

**Expected behavior**
The wither should not explode instantly.

**Videos**
Limits Version 1.15.0: https://youtu.be/E0Ra6yOstSA
Limits Version 1.14.0: https://youtu.be/ZECY0e8RKfc

**Server Information:**
 - Database being used: JSON
 - OS: Debian
 - Minecraft Version Paper 1.16.4 (git-Paper-322 (MC: 1.16.4))
 - Java Version: Java 11
 - BentoBox version: 1.15.3
 - Addons installed:
   - AcidIsland 1.14.5 (ENABLED)
   - Biomes 1.13.0 (ENABLED)
   - CaveBlock 1.14.1 (ENABLED)
   - Challenges 0.8.3 (ENABLED)
   - Chat 1.1.1 (ENABLED)
   - ControlPanel 1.7.0 (ENABLED)
   - DimensionalTrees 1.6.0 (ENABLED)
   - FrameMiner 1.2.1 (ENABLED)
   - Level 2.5.0 (ENABLED)
   - Likes 2.0.0 (ENABLED)
   - Limits 1.15.0 (ENABLED)
   - MagicCobblestoneGenerator 2.1.0 (ENABLED)
   - Warps 1.10.0 (ENABLED) 
 - Other plugins: WorldEdit, WorldGuard

**Comment by tastybento** [comment]
Fixed by 514f2158ccf67f3568f406e8be8c63c600fefac8

This means the wither check has to be sync.
