### ISSUE TITLE
Unlimited amounts of hoppers used

### ISSUE THREAD

**Issue by dushanbe7** [BentoBoxWorld/Limits#130]
**Description**
Use minecart with hopper. Once u hit the hopper limit just keep making those minecarts with hopper since its impossible to limit them through config.

**Steps to reproduce the behavior:**

**Expected behavior**
Minecart with hopper should be limited because u can use it instead hopper

**Screenshots**

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): []
 - Java Version: [e.g. Java 8]
 - BentoBox version: [e.g. 1.7.2.21]
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
 - Other plugins? [Do '/plugins' and copy/paste from the console]

**Additional context**

**Comment by tastybento** [comment]
Hopper minecarts are entities, so you can put MINECART_HOPPER in the entity list.

**Comment by dushanbe7** [comment]
Hello, ID for the item is HOPPER_MINECART. I just placed like you said and it works, but you see the confusion.  https://prnt.sc/123ya2m

**Comment by BONNe** [comment]
Well, it is easy to answer...
We do not come up with the names, SPIGOT did.
And they named it before mojang introduced ID names.

So... it is MINECART_HOPPER instead or minecraft:hopper_minecart.

**Comment by tastybento** [comment]
For future reference, the IDs are here for entities: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
