### ISSUE TITLE
Making a menu upgrade Hopper limits.

### ISSUE THREAD

**Issue by tienthanh23423** [BentoBoxWorld/Limits#133]
So in the config, the limit would be:
`blocklimits:`
`  HOPPERS: 10`
1.So what they did is like normal players would have a limit of 10 hoppers per player or per island?
2.If it is per player (or per island) then when I add `bskyblock.island.limit.hopper.20` then the limits will decrease to 20 hoppers right?

**Comment by tastybento** [comment]
1. Per island
2. Yes, the limit will *increase* to 20. However, only the island owner's permission counts.

**Comment by tastybento** [comment]
If you would like live support use our Discord: https://discord.gg/xMb5HTAN

**Comment by tienthanh23423** [comment]
> * Per island
> * Yes, the limit will _increase_ to 20. However, only the island owner's permission counts.

I don’t know anything about github, so sorry for the late reply. I used bettergui as a Gui plugin. So how do i check if that boi is owner of the island or not? Does owner of an island get a specific perm? So that i can easily check it in my menu config to prevent members of that island buy the limit

**Comment by tastybento** [comment]
Owners of an island do not get a specific perm. I'm not sure how you would/could check ownership for the plugin, sorry. I recommend asking on the Discord as some other admins might have a solution or some other ideas.

**Comment by tienthanh23423** [comment]
I ask them in discord yesterday and there is no one answering me. AlanVN#0234. Btw go discord and answer my question.
