### ISSUE TITLE
BentoBoxWorld / Limits

### ISSUE THREAD

**Issue by srrawr11** [BentoBoxWorld/Limits#137]
### Expected behavior

I would like to know if its posible to put limits on mobs? Like: Wolf, Ozelot, Llama, Parrot, etc etc.
Because I tried to put a limit for each island liek this..
![image](https://user-images.githubusercontent.com/73607495/128630550-252a7bec-dc9b-4ffb-9984-16575b38e5f3.png)
But is not working..

Thanks!

### Observed/Actual behavior

.

### Steps/models to reproduce

.

### BentoBox version

Gamemode: AOneBlock 1.5.5
Plugin BentoBox Verison: 1.16.2
BentoBox Limits Version: 1.15.5
Minecraft version: 1.16.5

### Plugin list

.

### Other

.

**Comment by tastybento** [comment]
Yes, it is possible. The screenshot of your config file _looks_ okay. When you say it isn't working, what isn't working? If you are Op, then you will be able to ignore all limits. Maybe that is the problem. What do you see when you do `/ob limits`?
