### ISSUE TITLE
Normal eggs can still spawn chickens when reach the limit.

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Limits#144]
### Expected behavior

![image](https://user-images.githubusercontent.com/47111280/133390731-5f631435-e74f-4d2a-9485-8184fe623b6e.png)
![image](https://user-images.githubusercontent.com/47111280/133390807-f61cfb92-185b-4b90-9f19-fc1683a3cc40.png)

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/47111280/133390887-b2d83e54-fdf9-47dc-8584-3ab458925766.png)
When it reaches the limit, no chicken should come out of the egg.

### Steps/models to reproduce

When it reaches the limit, no chicken should come out of the egg.

### BentoBox version

![image](https://user-images.githubusercontent.com/47111280/133391170-408aa9aa-15c1-4255-9a46-5bceed13d99b.png)

**Comment by tastybento** [comment]
That's weird! I wonder what changed!

**Comment by tastybento** [comment]
Hmm, I cannot replicate this. I am blocked from increasing chickens and see an error. However, with thrown eggs, the way the bypass is checked is to see if there is an Op player or a player with the bypass perm within a 10x10x10 box around the egg breaking location, so maybe this is what is happening.

**Comment by tastybento** [comment]
Try new version.
