### ISSUE TITLE
Hey! I want to ask for help with addon Limit. I need the limit on the island to be set on absolutely all living creatures (including animals and monsters) in the amount of 100 mobs per island. Can it be configured like this?

### ISSUE THREAD

**Issue by Pikachu2p** [BentoBoxWorld/Limits#145]
To make it like something kind of like this

entitylimits:
    limit: 100

OR

  entitylimits:
       ALLENTITES: 100

**Comment by tastybento** [comment]
Sorry, this isn't possible. You have name the specific entity type, not a generic thing.

**Comment by Pikachu2p** [comment]
Oh :( thanks
