### ISSUE TITLE
Limits not working, might have to do with #147

### ISSUE THREAD

**Issue by Jcodeerd** [BentoBoxWorld/Limits#148]
### Expected behavior

that there are island limits

### Observed/Actual behavior

no island limits

### Steps/models to reproduce

install limits
give ranks via luckperms the permission "aoneblock.limit.hopper."

### BentoBox version

10.10 13:22:55 [Server] INFO Running AIRPLANE 1.17.1.
10.10 13:22:55 [Server] INFO BentoBox version: 1.17.2
10.10 13:22:55 [Server] INFO Database: JSON
10.10 13:22:55 [Server] INFO Loaded Game Worlds:
10.10 13:22:55 [Server] INFO oneblock_world (OneBlock): Overworld, Nether
10.10 13:22:55 [Server] INFO Loaded Addons:
10.10 13:22:55 [Server] INFO AOneBlock 1.9.0-SNAPSHOT-b220 (ENABLED)
10.10 13:22:55 [Server] INFO Border 3.2.0 (ENABLED)
10.10 13:22:55 [Server] INFO ControlPanel 1.13.0 (ENABLED)
10.10 13:22:55 [Server] INFO Level 2.7.2 (ENABLED)
10.10 13:22:55 [Server] INFO Limits 1.17.2 (ENABLED)
10.10 13:22:55 [Server] INFO Visit 1.4.0 (ENABLED)
10.10 13:22:55 [Server] INFO Warps 1.11.1 (ENABLED)

### Plugin list

AdvancedBan, AntiAFK*, AntiDonkeyDupe, AuctionHouse, BanAnnouncer*, BentoBox, BuycraftX, ChunkHopper, Citizens, ClicksPerSecond*, CombatLogX, CommandCooldown, CoreProtect, CrateReloaded, DeluxeAnnounce, DeluxeTags, DiscordSRV, dynmap, EconomyShopGUI, EnderVaults, EpicGuard*, Essentials, EssentialsChat, EssentialsSpawn, GCore, GSit, Harbor, HeadDB, HolographicDisplays, IllegalStack, InventoryRollback, Item2Chat, JoinCommands, LPC, LuckPerms, MyCommand, NexEngine, PlaceholderAPI, PlugMan, ProtocolLib, QuickShop, Scoreboard-revision*, Sellwand, SilkSpawners, SirBlobmanCore (SirBlobmanAPI, XSeries), spark, Spicord*, StaffChat, STN-Studios-API, SuperVanish, TAB, Tamablefoxes, TCPShield, TempFly, TradeSystem, UltimateAutoRestart, Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, VotingPlugin, WorldBorderAPI, WorldEdit, WorldGuard

**Comment by FrontierPixelmon** [comment]
I found that limits doesn’t work with the Upgrades addon atm, that is why I was having that issue

**Comment by Jcodeerd** [comment]
Sorry, I made a typo
I gave 
![image](https://user-images.githubusercontent.com/68161666/136698807-38e35ef7-4aa3-422d-8ebe-db61e5248e23.png)
but /is limits or so doesnt do anything too

**Comment by FrontierPixelmon** [comment]
Gotcha, then what I would do is go look at my ticket and follow what he had me do, create a brand new server with only luckperms and bento box with the addon limits. If it works then add each addon in one by one to see if one of them makes it stop working
