### ISSUE TITLE
Bug of spawning mobs

### ISSUE THREAD

**Issue by luqsq** [BentoBoxWorld/Limits#151]
### Expected behavior

Block spawn new animals when player try reproduce animals over limit.

Block spawn new animals when player try spawn any mob by spawn egg.

### Observed/Actual behavior

Player can reproduce animals over limits or manually spawn mobs (spawn eggs).

### Steps/models to reproduce

Use spawn egg or try reproduce animals

### BentoBox version

![image](https://user-images.githubusercontent.com/89254138/147010347-7942910d-e3e4-49a9-b288-e308915a8def.png)

**Comment by tastybento** [comment]
What version of BentoBox are you using?

Is any error or message shown when the players try to spawn animals over the limit? What does the limit GUI show for the player?

Players can bypass the limit if they are Op, or if they have the bypass permission, like `bskyblock.mod.bypass` or `bskyblock.mod.*` so maybe it is a perm issue.

**Comment by luqsq** [comment]
Now I know that when the OP is next to player (who try, for example, reproduce animals over limit), the limit doesn't work.
This is stupid, because admins wouldn't be able to visit players islands...
Y**ou should also check that this person is a MEMBER OF THE ISLAND TEAM**. Please fix it.

**Comment by tastybento** [comment]
> Now I know that when the OP is next to player (who try, for example, reproduce animals over limit), the limit doesn't work.
> This is stupid, because admins wouldn't be able to visit players islands...
> Y**ou should also check that this person is a MEMBER OF THE ISLAND TEAM**. Please fix it.

I find your tone offensive.

**Comment by luqsq** [comment]
What? So you don't do anything about it, will you be offended?

**Comment by Poslovitch** [comment]
![image](https://user-images.githubusercontent.com/20014332/147404969-07d09a08-ce80-4c22-a19c-4f6c71f7d0ea.png)
