### ISSUE TITLE
animal/monster limit

### ISSUE THREAD

**Issue by rudde0** [BentoBoxWorld/Limits#195]
### Is your feature request related to a problem?

Some players are creating high amount of animal/monster farms which causing lag.

### Describe the solution you'd like.

Limits addon allows to limit entities by their types individiually but there should be wildcards such as `*` (maybe even `ANIMALS` and `MONSTERS` keys) to limit some entities by their category instead of single entity types. For example we should disable >256 animals and >128 monsters at total in the per island.

### Describe alternatives you've considered.

-

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
@rudde0 This change adds the Animals and Monsters to the config.yml as entity groups so you can customize them.
