### ISSUE TITLE
LIMITS BUG

### ISSUE THREAD

**Issue by mcwal18** [BentoBoxWorld/Limits#230]
### Expected behavior

I will show you in a video, so you guys can see it.
- Paper 1.21.1
- Limits-1.25.0.jar
Link: https://i.imgur.com/GNrcsss.mp4

It works as USER and as an OP!

### Observed/Actual behavior

.

### Steps/models to reproduce

.

### BentoBox version

BentoBox-2.7.0.jar

### Plugin list

.

### Other

.

**Comment by tastybento** [comment]
Are there any errors in the console when this happens?

**Comment by mcwal18** [comment]
> Are there any errors in the console when this happens?

Nope, nothing.

**Comment by tastybento** [comment]
Weird. How did you set the max hopper value? In config.yml or via permissions?

If you place the hoppers slowly, do you still see this?

**Comment by mcwal18** [comment]
> Weird. How did you set the max hopper value? In config.yml or via permissions?
> 
> If you place the hoppers slowly, do you still see this?

Hi, this is the config I have in the config.yml
https://pastebin.com/ABZFeiR2

And I have put the perm: - aoneblock.island.limit.hopper.50 to my default users.
Am using LuckPerms btw.

**Comment by mcwal18** [comment]
![image](https://github.com/user-attachments/assets/5c6a305f-09c9-4dfd-8104-f1d175704c67)

That's what they told me.

**Comment by tastybento** [comment]
@mcwal18 Okay, I can do that. That is not a normal thing, and I haven't heard of that before.

**Comment by tastybento** [comment]
@mcwal18 Try https://ci.codemc.io/job/BentoBoxWorld/job/Limits/ - that has the change in it.

**Comment by mcwal18** [comment]
> @mcwal18 Try https://ci.codemc.io/job/BentoBoxWorld/job/Limits/ - that has the change in it.

Hey! The problem is that.. am using PAPER 1.21.1 with BENTOBOX 2.7.0 and this addon is not working on it..
And the latest version of BENTOBOX 3.0.1 doesn't support it..

**Comment by tastybento** [comment]
> > @mcwal18 Try https://ci.codemc.io/job/BentoBoxWorld/job/Limits/ - that has the change in it.
> 
> Hey! The problem is that.. am using PAPER 1.21.1 with BENTOBOX 2.7.0 and this addon is not working on it.. And the latest version of BENTOBOX 3.0.1 doesn't support it..

Okay, no problem - I put the change into https://github.com/BentoBoxWorld/Limits/releases/tag/1.25.1

**Comment by mcwal18** [comment]
> > > @mcwal18 Try https://ci.codemc.io/job/BentoBoxWorld/job/Limits/ - that has the change in it.
> > 
> > 
> > Hey! The problem is that.. am using PAPER 1.21.1 with BENTOBOX 2.7.0 and this addon is not working on it.. And the latest version of BENTOBOX 3.0.1 doesn't support it..
> 
> Okay, no problem - I put the change into https://github.com/BentoBoxWorld/Limits/releases/tag/1.25.1

That;s it, working fine, thanks for your time and effort! <3
