### ISSUE TITLE
Unable to limit Item Frames, Paintings, and Armor Stands

### ISSUE THREAD

**Issue by Deathinflames** [BentoBoxWorld/Limits#24]
**Description**
I can't seem to limit Item Frames, Paintings, and Armor Stands with the BentoBox Limits addon.

**Steps to reproduce the behavior:**
1. Stop server
2. Open your /plugins/BentoBox/addons/Limits/config.yml
3. Add the following to config.yml under "blocklimits:"
```
  ITEM_FRAME: 100
  PAINTING: 100
  ARMOR_STAND: 100
```

4. Start server and notice in console
> [BentoBox] [Limits] Material ITEM_FRAME is not a valid block. Skipping...
> [BentoBox] [Limits] Material PAINTING is not a valid block. Skipping...
> [BentoBox] [Limits] Material ARMOR_STAND is not a valid block. Skipping...

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): YAML
 - OS: [e.g. iOS]: Ubuntu 16.04
 - Java Version: [e.g. Java 8]: Java 8 (build 1.8.0_212)
 - BentoBox version: [e.g. 1.7.2.21]: 1.5.2
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]

Running PAPER 1.13.2.

Loaded Addons:
Biomes 1.5.0.0 (ENABLED)
BSkyBlock 1.5.0 (ENABLED)
Challenges 0.7.5 (ENABLED)
Level 1.5.0 (ENABLED)
Limits 0.2.1-SNAPSHOT (ENABLED)
WelcomeWarps 1.5.0 (ENABLED)

**Comment by tastybento** [comment]
Try putting these in the Entity Limits instead. I know that these can be classed as entities and not blocks. However, I think these are "weird" because of this hybrid nature. They may need special handling.

**Comment by Deathinflames** [comment]
Well, the good news is adding armor stands to entitylimits allowed that to start being limited. The bad news is paintings and item frames are still showing as not supported.

> [BentoBox] [Limits] Entity type: ITEM_FRAME is not supported - skipping...
> [BentoBox] [Limits] Entity type: ITEM_FRAME is not supported - skipping...

**Comment by tastybento** [comment]
This should work: https://github.com/BentoBoxWorld/Limits/releases/tag/0.2.3-rc

**Comment by OverBrave** [comment]
ITEM_FRAME problem contiunes...
`[20:11:56] [Server thread/ERROR]: [BentoBox] [Limits] Entity type: ITEM_FRAME is not supported - skipping...`
![image](https://user-images.githubusercontent.com/47111280/73881805-0d031980-4872-11ea-9695-d51d80ec9841.png)
