### ISSUE TITLE
items prevented from being placed

### ISSUE THREAD

**Issue by ronc617** [BentoBoxWorld/Limits#30]
![image](https://user-images.githubusercontent.com/36974241/60268666-ec75e880-98ba-11e9-86f6-0dc43e907fd5.png)

Using the latest version of limits
animals cant be leashed  getting the following message
![image](https://user-images.githubusercontent.com/36974241/60268574-acaf0100-98ba-11e9-9d5f-7b7e4259f801.png)

also item frames cant be placed
![image](https://user-images.githubusercontent.com/36974241/60269093-cc92f480-98bb-11e9-8064-2385f92e787a.png)

the only thing in config is for hopper limit

**Comment by tastybento** [comment]
Thanks!
