### ISSUE TITLE
Critical - Not block detect

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Limits#42]
**Description**
The limit addon sometimes does not detect that the blocks are broken.

**Screenshots**
![image](https://user-images.githubusercontent.com/47111280/64212433-08e16300-ceb2-11e9-8dfb-788b00b8b3b6.png)
![image](https://user-images.githubusercontent.com/47111280/64212542-5362df80-ceb2-11e9-829b-24760c0ca0af.png)
![image](https://user-images.githubusercontent.com/47111280/64212545-5958c080-ceb2-11e9-8c7d-24eea83c0db1.png)
![image](https://user-images.githubusercontent.com/47111280/64212548-5d84de00-ceb2-11e9-9b82-b6035c9d580b.png)

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): [JSON]
 - OS: Windows
 - Java Version:  Java 8
 - BentoBox version:
![image](https://user-images.githubusercontent.com/47111280/64212483-27dff500-ceb2-11e9-8522-1b584e63a20c.png)

**Comment by tastybento** [comment]
Do you know how the blocks are broken?

**Comment by OverBrave** [comment]
No

**Comment by tastybento** [comment]
I know that if another plugin destroys a block Limits will not detect it. Also, there may be some other way to destroy blocks without causing an event (or maybe an event I am not catching). 

If you find out how to break blocks or have an idea, let me know because I can't do much without that. You can run the admin calc command to recount items on the island as a workaround.

**Comment by tastybento** [comment]
I added a recount command for players. See the latest commit. There are ways to break blocks and not catch the breaking unfortunately.

**Comment by OverBrave** [comment]
I think I figured out what the problem was. The egg doesn't count when it breaks on its own. Or the player doesn't count that as soon as he digs silky.

**Comment by OverBrave** [comment]
The problem is still unsolved.
