### ISSUE TITLE
Minecart limits not working correctly

### ISSUE THREAD

**Issue by Tina-King** [BentoBoxWorld/Limits#48]
**Description**
I am able to limit minecarts but I can not limit hopper_minecart, chest_minecart, furnace_minecart and tnt_minecart

**Steps to reproduce the behavior:**
Use this config and you will see you are only limited on 16 normal minecarts:
entitylimits:
  MINECART: 16
  HOPPER_MINECART: 16
  CHEST_MINECART: 16
  TNT_MINECART: 8
  FURNACE_MINECART: 8

**Expected behavior**
The other minecart types should be limited

**Screenshots**
https://puu.sh/EkR86/0e03df303c.png

**Server Information:**
Version: 1.14.4

**Comment by tastybento** [comment]
In the wonderful world of Minecraft/Bukkit, Minecarts are entities, so you will need to use the [entity type name](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html) for them:

```
  MINECART: 16
  MINECART_HOPPER: 16
  MINECART_CHEST: 16
  MINECART_TNT: 8
  MINECART_FURNACE: 8
```

**Comment by Tina-King** [comment]
Hi,

If you read the initial question I did put it in entity limits.

I am able to limit minecarts but not any hopper minecarts, chest minecarts, tnt minecarts or funnace minecarts.

Thanks

**Comment by BONNe** [comment]
It is because you are doing it with wrong entity names.

**Comment by Tina-King** [comment]
I actually wrote my bug report incorrectly before, here are the entity IDs I am using. They are not being limited and the entity IDs are correct.

`entitylimits:
  MINECART: 16
  HOPPER_MINECART: 16
  CHEST_MINECART: 8
  TNT_MINECART: 8
  FURNACE_MINECART: 8
  ENDERMAN: 5
  CHICKEN: 10
  pig_ZOMbIe: 15`

The minecarts are not being limited, except the normal minecart.

**Comment by Tina-King** [comment]
Sorry guys! You are right and I must have been half asleep, it works perfectly fine.

**Comment by tastybento** [comment]
ah, okay - I was just firing everything back up to double check! Glad it works for you. Have fun!
