### ISSUE TITLE
Build #174 problem

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Limits#50]
**Description**
Only when update limits addon 174 or above give this error .

**Screenshots**
![image](https://user-images.githubusercontent.com/47111280/68531699-2c97ae00-0326-11ea-959d-85e017a7c800.png)

**Comment by tastybento** [comment]
Guava Immutable map doesn't allow null values. I'll fix.

**Comment by tastybento** [comment]
Thanks.
