### ISSUE TITLE
Is Limits Recount <playername>

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/Limits#52]
**Is your feature request related to a problem? Please describe.**
Block count files sometimes do not represent the reality on islands. I suspect several scenarios under which this could happen. My suspicion so far:
- island deletion/purging
- altering limits/existing islands not recalculated

**Describe the solution you'd like**
Command to recalculate a particular island by an admin. Something like `/bsbadmin limits recount <playername>` or `is limits recount <playername>`

**Describe alternatives you've considered**
The existing command `is limits recount` can only be executed by the player itself.
Since we can't force a player to execute this, we need to do it for them.
I tried adding the command to bskyblock's `island.commands.on-join` but this does not work.
The command really needs to be executed "as player".
Editing database files manually is not an option either

**Additional context**

**Comment by tastybento** [comment]
There is already an admin command `/bsb limits calc <playername>`. Does it work?

**Comment by x1p** [comment]
I didn't know this command existed.
I recalculated, but I doubt it is correct.

**Comment by tastybento** [comment]
Okay. I ported over the latest code from the Level addon. This has multi-threaded block counting and should work great. It requires BentoBox 1.9.0-SNAPSHOT or later
