### ISSUE TITLE
Placeholder: %[gamemode]_limits_#MATERIAL#_count/max% 

### ISSUE THREAD

**Issue by Bricec6** [BentoBoxWorld/Limits#56]
Hello, I think a new feature in the Limits addon would be very useful to improve the bentobox plugin, it's the addition of placeholder of the /is limits.

Ex:
%bskyblock_limits_hopper% = displays the X/MAX hoppers of the island
%bskyblock_limits_hopper_#OWNER% = displays the X/MAX hoppers of the island to another player

it will allow you to see who has what on your island etc. via a custom DM menu.

thank you

**Comment by Poslovitch** [comment]
Our API for placeholders currently does not allow us to have "parameters" inside them. We, therefore, cannot create these placeholders until this not doable.
I will open a feature request on BentoBox's issue tracker.

**Comment by Bricec6** [comment]
up
