### ISSUE TITLE
Per World limiting

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/Limits#58]
**Description**
Limiting blocks (blocklimits) per world counts as if all worlds count.
Example:
```
blocklimits:
  HOPPER: 500
worlds:
  bskyblock_world_nether:
    HOPPER: 50
```
If the overworld has >50 hoppers, no hopper is allowed to be placed in the nether.
My own logic would count as follows:
450 hoppers in the overworld and 50 in the nether.
or 500 hoppers in the overworld of course.

**Steps to reproduce the behavior:**
1. Set limits as above
2. Place 45 hoppers in the overworld
3. Go to the nether and place as many as you can
4. See that only 5 hoppers are possible, despite the limit of 50.

**Expected behavior**
Limiting things per world would imho not include numbers in the global limit if per world is more strict than global

**Screenshots**

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): [JSON]
 - OS: [Linux]
 - Java Version: [OpenJDK 1.8.0]
 - BentoBox version: [1.9.0 b1493]
 - Addons installed?
```
Running PAPER 1.14.4.
BentoBox version: 1.9.0-SNAPSHOT-b1493
Database: JSON
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, End
Loaded Addons:
Biomes 1.6.0.1-SNAPSHOT-b149 (ENABLED)
BSkyBlock 1.9.0-SNAPSHOT-b525 (ENABLED)
Challenges 0.9.0-SNAPSHOT-#393 (ENABLED)
Level 1.9.0-SNAPSHOT-b309 (ENABLED)
Limits 1.9.0-SNAPSHOT-b179 (ENABLED)
MagicCobblestoneGenerator 1.7.0.2 (ENABLED)
Warps 1.8.2-SNAPSHOT-b201 (ENABLED)
```
 - Other plugins? [BentoBox, ChestShop, dynmap*, LuckPerms, mcMMO, PlaceholderAPI*, PlugMan, Vault, WorldBorder, WorldEdit, WorldGuard]

**Additional context**

**Comment by tastybento** [comment]
The calculations are like this because currently the nether and end are all summed with the over world. I.e., the “world” for a game mode = overworld + nether + end. The config for other worlds is for game mode worlds like AcidIsland or Caveblock. 

Is there some need to really limit a player by environment/dimension? If so then this is an enhancement that can be considered.

**Comment by x1p** [comment]
Hmm strange logic but ok.
Thanks though.
I will discuss internally what to do with this.
