### ISSUE TITLE
Cannot put ender eye into end portal frame

### ISSUE THREAD

**Issue by frengor** [BentoBoxWorld/Limits#71]
**Description**
When end portal frame is limited to 1 you cannot place an ender eye in it.

**Steps to reproduce the behavior:**
1. Limit END_PORTAL_FRAME to 1.
2. Place an end portal frame.
3. Right click with an ender eye on it.

**Screenshots**
![2020-03-12_17 46 18](https://user-images.githubusercontent.com/31711263/76545142-856c8400-6489-11ea-820c-c7207febae6c.png)

**Server Information:**

 - OS: Windows
 - Java Version: Java 8
 - Version:  Running SPIGOT 1.15.2.
 - BentoBox version: 1.12.0-SNAPSHOT-b1679
 - Database: JSON
 - Loaded Game Worlds: bskyblock_world (BSkyBlock): Overworld, Nether, The End
 - Loaded Addons:
Biomes 1.6.0.1 (ENABLED)
Border 1.0.6-SNAPSHOT-LOCAL (ENABLED)
BSkyBlock 1.11.0 (ENABLED)
Chat 1.0.4 (ENABLED)
ControlPanel 1.7.0 (ENABLED)
Level 1.9.3 (ENABLED)
Limits 1.9.2 (ENABLED)
TwerkingForTrees 1.1.2 (ENABLED)
Warps 1.9.0 (ENABLED)

**Comment by tastybento** [comment]
Cannot replicate with 1.19.1 Limits, so this seems to work.
