### ISSUE TITLE
entity limit bug

### ISSUE THREAD

**Issue by arts7493** [BentoBoxWorld/Limits#78]
#### Describe the bug

player has bee limit permission but changed chicken limit size 

#### Expected behavior

permission
#### Screenshots and videos (Optional)

![image](https://user-images.githubusercontent.com/3336813/80512152-09d28200-89b8-11ea-9d3f-f53937617868.png)

config 
[config.txt](https://github.com/BentoBoxWorld/BentoBox/files/4547158/config.txt)

##### BentoBox Version (Mandatory)

```
Running PAPER 1.15.2.
BentoBox version: 1.12.0
Database: JSON
 Loaded Game Worlds:
 bskyblock_world (BSkyBlock): Overworld, [nether_color]Nether, [end_color]End
Loaded Addons:
 Biomes 1.7.0 (ENABLED)
 BSkyBlock 1.12.0 (ENABLED)
Level 1.9.3 (ENABLED)
Limits 1.9.4 (ENABLED)
```

#### Plugins (Optional)

```
_______
```

**Comment by tastybento** [comment]
See [known issues in the release](https://github.com/BentoBoxWorld/Limits/releases) - bees cannot be tracked correctly with this addon.
The chicken thing looks suspicious. Are you sure that player doesn't have another permission? Is this repeatable easily?

**Comment by arts7493** [comment]
> See [known issues in the release](https://github.com/BentoBoxWorld/Limits/releases) - bees cannot be tracked correctly with this addon.
> The chicken thing looks suspicious. Are you sure that player doesn't have another permission? Is this repeatable easily?

yes. player doesn't have other permission.
and if player has bee or chicken perm, it has be changes chicken or bee limit size

**Comment by tastybento** [comment]
Okay, weird. I'll look into it.

**Comment by tastybento** [comment]
I think this is related to #79

**Comment by tastybento** [comment]
Try 1.12.1. I think this is due to a mixing of perms bug.
