### ISSUE TITLE
Limit Permissions Affective Other Players

### ISSUE THREAD

**Issue by Rubenicos** [BentoBoxWorld/Limits#79]
**Description**
I gave myself bskyblock.island.limit.ENDERMAN.70 permission for 6 hours (I use LuckPerms) and now all players have the 70 endermans limit

**Expected behavior**
temporal permission

**Screenshots**
I'm the only one who has the permission
![Captura de pantalla (217)](https://user-images.githubusercontent.com/44579213/80759271-41dedf80-8af4-11ea-9fe2-a63bed37606b.png)
But when checking the limits of other players they also have the same limit
![Captura de pantalla (218)](https://user-images.githubusercontent.com/44579213/80759393-79e62280-8af4-11ea-9895-d819b9c8a247.png)

**Server Information:**

 - Database being used: MySQL 
 - Java Version: Java 11
-  Running Tunity 1.15.2
 - BentoBox version: 1.12.0
 - Addons installed:
  Biomes 1.6.0.1 (ENABLED)
  BSkyBlock 1.12.0 (ENABLED)
  Challenges 0.9.0-SNAPSHOT-b400 (ENABLED)
  Chat 1.0.4 (ENABLED)
  Level 1.9.4-SNAPSHOT-b345 (ENABLED)
  Limits 1.9.4 (ENABLED)
  Warps 1.9.0 (ENABLED)

**Comment by tastybento** [comment]
How are you checking that other players have this limit? Please give step by step instructions.

**Comment by Rubenicos** [comment]
1. First of all, I gave myself permission.
2. Then I left the server and went back in.
3. I used the /is limits command to verify that the change had been applied (if it was applied)
4. Then I used /bsbadmin limits <player> to check the limits of any other player and they all had the same endermans limit as me.
5. I told the other players to use the /is limits command and check the endermans limit, they all said they now have a limit up to 70 endermans.

**Comment by tastybento** [comment]
Thanks. I can replicate this. Now I need to try and find out why it's happening.

**Comment by tastybento** [comment]
Found the bug.

**Comment by tastybento** [comment]
I did a new release 1.12.1 that has this fix in. Please try it.
