### ISSUE TITLE
Entity/Block limits cleared on player join

### ISSUE THREAD

**Issue by Guillaume-Lebegue** [BentoBoxWorld/Limits#83]
**Is your feature request related to a problem? Please describe.**
I'm developing an addon and I'm setting the entity and block limits to different values.
(For upgrading the limits)
But when players join the island, this data is cleared for setting a new one with the permission.

**Describe the solution you'd like**
I would like a way to disable that

**Comment by tastybento** [comment]
I could fire an event and then you could cancel it?

**Comment by Guillaume-Lebegue** [comment]
That's a good idea

**Comment by tastybento** [comment]
Have a look at the latest snapshot and ad186958ccd0b2ee34c97260589bf176716809db and let me know if it works for you.

**Comment by Guillaume-Lebegue** [comment]
Perfect, that solved my problem
