### ISSUE TITLE
Default limits with 1.16

### ISSUE THREAD

**Issue by Guillaume-Lebegue** [BentoBoxWorld/Limits#85]
**Description**
Default configuration with pig_ZOMbIe create an error on minecraft 1.16

**Steps to reproduce the behavior:**
Clean install on 1.16

**Additional context**
I think the name pig_ZOMbIe was changed in 1.16.
Maybe just remove it from the default configuration file.

**Comment by Espantonius** [comment]
The name has changed, now called: ZOMBIFIED_PIGLIN
