### ISSUE TITLE
Option to disable or reduce notifier concept for island limits.

### ISSUE THREAD

**Issue by Weymouth87** [BentoBoxWorld/Limits#89]
#### Is your feature request related to a problem?

When a mob limit is reached, the user recieves multiple messages regarding it. 

#### Describe the solution you'd like us to implement.

I would love the option to reduce these messages to 1 or disable them entirely.

### Additional context

![image](https://user-images.githubusercontent.com/20014332/88631425-6b3ae780-d0b2-11ea-8307-e5a45871b5fa.png)
Screenshot for context

**Comment by tastybento** [comment]
The notification is already used, so one message should be sent a maximum of every 4 seconds. How is this message being generated? What is spawning the Endermen?

**Comment by Weymouth87** [comment]
It was from an enderman spawner. Just when the player reached the limit for their spawning, it sent the messages. I was just looking for it to send once, rather than every x seconds :)

**Comment by tastybento** [comment]
It should only send it once if they are at the limit and then only send it again when the spawner tries to spawn again. How fast does the spawner spawn? Also, you will only see a message if you are within 5 blocks of the spawner.
