### ISSUE TITLE
Config Issues

### ISSUE THREAD

**Issue by teagan75** [BentoBoxWorld/Limits#91]
**Description**
Am I adding things to the config wrong because my additions are not showing up in game.

**Steps to reproduce the behavior:**
1. Install BSkyBlock and limits
2. Add entities to config
3. Start server and open the limits GUI
4. See new additions or not

**Expected behavior**
I expect the limits I added to the config to show up in the Limits GUI in game

**Config**
https://pastebin.com/ZEBYU4Lr

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): [JSON]
 - OS: not sure. I run a server through Host Havoc on Multicraft
 - Java Version: Java 8
 - BentoBox version: 1.14.2
##### Output of `/bbox version` (Mandatory)

```
06.08 21:46:11 [Server] Server thread/INFO Running SPIGOT 1.16.1.
06.08 21:46:11 [Server] Server thread/INFO BentoBox version: 1.14.2
06.08 21:46:11 [Server] Server thread/INFO Database: JSON
06.08 21:46:11 [Server] Server thread/INFO Loaded Game Worlds:
06.08 21:46:11 [Server] Server thread/INFO bskyblock_world (BSkyBlock): Overworld, Nether, The End
06.08 21:46:11 [Server] Server thread/INFO Loaded Addons:
06.08 21:46:11 [Server] Server thread/INFO BSkyBlock 1.13.1 (ENABLED)
06.08 21:46:11 [Server] Server thread/INFO Challenges 0.8.4-SNAPSHOT-b428 (ENABLED)
06.08 21:46:11 [Server] Server thread/INFO Chat 1.0.4 (ENABLED)
06.08 21:46:11 [Server] Server thread/INFO ExtraMobs 1.11.0.3 (ENABLED)
06.08 21:46:11 [Server] Server thread/INFO Greenhouses 1.2.0-SNAPSHOT-b242 (ENABLED)
06.08 21:46:11 [Server] Server thread/INFO Level 2.3.3 (ENABLED)
06.08 21:46:11 [Server] Server thread/INFO Limits 1.14.0 (ENABLED)
06.08 21:46:11 [Server] Server thread/INFO MagicCobblestoneGenerator 2.0.0 (ENABLED)
06.08 21:46:11 [Server] Server thread/INFO TwerkingForTrees 1.4.1 (ENABLED)
06.08 21:46:11 [Server] Server thread/INFO Upgrades 0.2.0-SNAPSHOT-b62 (ENABLED)
06.08 21:46:11 [Server] Server thread/INFO Warps 1.9.7 (ENABLED)

```

```
06.08 21:46:51 [Server] Server thread/INFO Plugins (4): Vault, BentoBox, PlayerKits, XConomy
```

**Additional context**

**Comment by tastybento** [comment]
Weird. I tried your file and it seems to work, however, there was a weird space in it that caused a number of the lines to be indented. I'm not sure if that was the problem. Anyway, this file works fine:

[config.yml.zip](https://github.com/BentoBoxWorld/Limits/files/5039232/config.yml.zip)

**Comment by teagan75** [comment]
Changing mine out for yours fixed the issue - whatever it was hehe. Thanks
