### ISSUE TITLE
wither boss bug

### ISSUE THREAD

**Issue by Bricec6** [BentoBoxWorld/Limits#93]
**Description**
Hello there is a problem with the limits of the island and the wither_heads, if you spawn a wither_boss the wither_heads will disappear but the island will still count that there are wither_heads and will count within the limit, the problem is that after a while the player will not be able to put more skeleton wither_heads because he will have spawned too many wither bosses.
**Server Information:**

[Please complete the following information:]
 - Database being used MARIA
 - OS: DEBIAN 9
 - BentoBox version: 1.4.2
 - Addons installed? 
![image](https://user-images.githubusercontent.com/51750055/91164666-b8b96d00-e6cf-11ea-8acf-1d473617b6cf.png)

**Comment by tastybento** [comment]
I understand the problem, but what is the use case for limiting wither heads? They disappear when the wither is generated, so why try to limit them?

**Comment by tastybento** [comment]
This should be fixed now in the latest snapshot.
