### ISSUE TITLE
JetsMinions turning to armor_stands in Limits build 229 and higher

### ISSUE THREAD

**Issue by Brian-TP** [BentoBoxWorld/Limits#99]
On our server we updated the limits addon a couple of days ago from the 228 build to the 230 build. Players said that when placing a minion on their bskyblock island the minion turned into a armor stand.

Today i tried updating the limits addon to build 231 and 232 but the problem was there also. It seems that when using the JetsMinions plugin the latest limits working build is 228.

The problem only seems to be in the gamemode worlds. When placing a minion on a default world (like a hub world) the minion does not turn into a armor_stand

Plugin information:
Bentobox 1.15.1 b1867
JetsMinions 6.4.9

**Comment by tastybento** [comment]
Try the latest snapshot when it builds and tell me if that helps.

**Comment by Brian-TP** [comment]
I have installed the latest build and kept everything else the same.
Minions no longer get turned into armor stands.
